# Generated by Django 4.2.4 on 2023-09-12 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_remove_attributevalue_attribute_remove_media_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 12, 13, 0, 52, 612246, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='media',
            field=models.FileField(default=datetime.datetime(2023, 9, 12, 13, 0, 59, 296933, tzinfo=datetime.timezone.utc), upload_to='patterns/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
