# Generated by Django 4.2.4 on 2023-09-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
