# Generated by Django 4.2.4 on 2023-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_delete_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Phone',
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(default='Write down...', max_length=15, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
