# Generated by Django 4.2.4 on 2023-09-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_remove_message_phone_message_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='phone',
            new_name='Phone',
        ),
    ]
