# Generated by Django 4.2.4 on 2023-09-26 16:02

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_rename_phone_message_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', django_ckeditor_5.fields.CKEditor5Field(verbose_name='تگ های جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
