# Generated by Django 4.2.4 on 2023-09-27 08:09

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_extratags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratags',
            name='field',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='تگ های جدید'),
        ),
    ]
