# Generated by Django 4.2.4 on 2023-09-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='dynamic_attributes',
        ),
        migrations.AddField(
            model_name='course',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='course.courseattribute'),
        ),
    ]
