# Generated by Django 4.2.4 on 2023-09-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_attributes_course_dynamic_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dynamic_attributes',
        ),
        migrations.CreateModel(
            name='CourseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
