# Generated by Django 4.2.4 on 2023-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_dynamic_attributes_courseattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='courseattribute',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دوره'),
        ),
        migrations.AlterField(
            model_name='courseattribute',
            name='key',
            field=models.CharField(max_length=100, verbose_name='نام ویژگی'),
        ),
        migrations.AlterField(
            model_name='courseattribute',
            name='value',
            field=models.CharField(max_length=255, verbose_name='مقدار ویژگی'),
        ),
    ]
