# Generated by Django 4.2.4 on 2023-09-14 11:53

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_options_alter_courseattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/course'),
        ),
    ]
