# Generated by Django 4.2.4 on 2023-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_alt_course_description_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='images/course'),
        ),
    ]
