# Generated by Django 4.2.4 on 2023-09-23 05:48

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_image_course_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='course',
            name='canonical',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Canonical'),
        ),
        migrations.AddField(
            model_name='course',
            name='descriptionOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:description'),
        ),
        migrations.AddField(
            model_name='course',
            name='heightOg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:height'),
        ),
        migrations.AddField(
            model_name='course',
            name='localeOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:locale'),
        ),
        migrations.AddField(
            model_name='course',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='course',
            name='site_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:site_name'),
        ),
        migrations.AddField(
            model_name='course',
            name='titleOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:title'),
        ),
        migrations.AddField(
            model_name='course',
            name='typeOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:type'),
        ),
        migrations.AddField(
            model_name='course',
            name='widthOg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:width'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
