# Generated by Django 4.2.4 on 2023-09-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='course',
        ),
    ]
