# Generated by Django 4.2.4 on 2023-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='href',
            field=models.CharField(default='Type...', max_length=100, verbose_name='کلاس'),
        ),
    ]
