# Generated by Django 4.2.4 on 2023-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_pagetags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='images/course'),
        ),
    ]
