# Generated by Django 4.2.4 on 2023-09-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_tags_canonical'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetags',
            name='canonical',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Canonical'),
        ),
    ]
