# Generated by Django 4.2.4 on 2023-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_pagetags_canonical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.TextField(default='Type...'),
        ),
        migrations.AlterField(
            model_name='pagetags',
            name='follow_nofollow',
            field=models.CharField(blank=True, choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pagetags',
            name='index_noindex',
            field=models.CharField(blank=True, choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=150, null=True),
        ),
    ]
