# Generated by Django 4.2.4 on 2023-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_delete_tags_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=models.FileField(upload_to='images/cover/course'), upload_to='images/course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.FileField(upload_to='images/cover/course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='Type...', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='media',
            field=models.FileField(upload_to='videos/course'),
        ),
    ]
