# Generated by Django 4.2.4 on 2023-09-11 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='Image')),
                ('alt', models.CharField(max_length=100, verbose_name='Alt')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 9, 11, 14, 18, 37, 614222), verbose_name='Publish Date')),
                ('pagetitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('canonical', models.CharField(blank=True, max_length=500, null=True, verbose_name='Canonical')),
                ('localeOg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:locale')),
                ('typeOg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:type')),
                ('titleOg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:title')),
                ('descriptionOg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:description')),
                ('site_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:site_name')),
                ('widthOg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:width')),
                ('heightOg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:height')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
