# Generated by Django 4.2.4 on 2023-09-11 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 14, 42, 55, 967992), verbose_name='Publish Date'),
        ),
    ]
