# Generated by Django 4.2.4 on 2023-09-12 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_pub_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 11, 37, 56, 333264), verbose_name='Publish Date'),
        ),
    ]
