# Generated by Django 4.2.4 on 2023-09-12 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 14, 39, 14, 435208), verbose_name='Publish Date'),
        ),
    ]
