# Generated by Django 4.2.4 on 2023-09-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_article_alt_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='article', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
