# Generated by Django 4.2.4 on 2023-09-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='type', unique=True, verbose_name='Slug'),
        ),
    ]
