# Generated by Django 4.2.4 on 2023-09-22 21:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='slug', editable=False, populate_from='title', unique=True, verbose_name='اسلاگ'),
        ),
    ]
