# Generated by Django 4.2.4 on 2023-09-27 08:57

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_tags_extratag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='schema1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='اسکیما'),
        ),
        migrations.AddField(
            model_name='tags',
            name='schema2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='اسکیما'),
        ),
    ]
