# Generated by Django 4.2.4 on 2023-09-27 09:00

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_tags_schema1_tags_schema2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='schema1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='اسکیما'),
        ),
        migrations.AddField(
            model_name='article',
            name='schema2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='اسکیما'),
        ),
    ]
