# Generated by Django 4.2.4 on 2023-09-27 09:04

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_article_schema1_article_schema2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extratag',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='تگ های جدید'),
        ),
    ]
