# Generated by Django 4.2.4 on 2023-09-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='canonical',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Canonical'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='descriptionOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:description'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='heightOg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:height'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='localeOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:locale'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='site_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:site_name'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='titleOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:title'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='typeOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:type'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pattern',
            name='widthOg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:width'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='PatternPostViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('pattern_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattern.pattern')),
            ],
        ),
    ]
