# Generated by Django 4.2.4 on 2023-09-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0005_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
