# Generated by Django 4.2.4 on 2023-09-23 18:48

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0007_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patternimage',
            old_name='description',
            new_name='body',
        ),
        migrations.AddField(
            model_name='pattern',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Type please...', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patternimage',
            name='alt',
            field=models.CharField(default='Alt', max_length=100, verbose_name='Alt'),
        ),
    ]
