# Generated by Django 4.2.4 on 2023-09-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0009_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Pattern Page Tag', 'verbose_name_plural': 'Pattern Page Tags'},
        ),
    ]
