# Generated by Django 4.2.4 on 2023-09-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0010_alter_tags_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
