# Generated by Django 4.2.4 on 2023-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0016_delete_patternimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='canonical',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Canonical'),
        ),
        migrations.AddField(
            model_name='tags',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Tags', verbose_name='تصویر'),
        ),
    ]
