# Generated by Django 4.2.4 on 2023-09-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0017_tags_canonical_tags_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='follow_nofollow',
            field=models.CharField(choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=150),
        ),
        migrations.AddField(
            model_name='pattern',
            name='index_noindex',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=150),
        ),
        migrations.AddField(
            model_name='pattern',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter:description'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter:title'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='extratag',
            field=models.TextField(blank=True, null=True, verbose_name='تگ های جدید'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='schema1',
            field=models.TextField(blank=True, null=True, verbose_name='اسکیما'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='schema2',
            field=models.TextField(blank=True, null=True, verbose_name='اسکیما'),
        ),
    ]
