# Generated by Django 4.2.4 on 2023-09-17 11:36

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamplesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام طرح')),
                ('title', models.CharField(max_length=250, verbose_name='عتوان طرح')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('author', models.CharField(choices=[('Z', 'ضیائی'), ('K', 'کارآموز')], default='Z', max_length=1, verbose_name='توسط')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('video', models.FileField(upload_to='video/samples', verbose_name='ویدیو طرح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت')),
                ('category', models.ManyToManyField(related_name='samples', to='samples.samplescategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح ها',
            },
        ),
    ]
