# Generated by Django 4.2.4 on 2023-09-24 09:14

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Type...', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samples',
            name='canonical',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Canonical'),
        ),
        migrations.AddField(
            model_name='samples',
            name='descriptionOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:description'),
        ),
        migrations.AddField(
            model_name='samples',
            name='heightOg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:height'),
        ),
        migrations.AddField(
            model_name='samples',
            name='localeOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:locale'),
        ),
        migrations.AddField(
            model_name='samples',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='samples',
            name='site_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:site_name'),
        ),
        migrations.AddField(
            model_name='samples',
            name='titleOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:title'),
        ),
        migrations.AddField(
            model_name='samples',
            name='typeOg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Og:type'),
        ),
        migrations.AddField(
            model_name='samples',
            name='widthOg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Og:image:width'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
