# Generated by Django 4.2.4 on 2023-09-15 09:23

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='samples',
            options={'verbose_name': 'طرح', 'verbose_name_plural': 'طرح ها'},
        ),
        migrations.AlterField(
            model_name='samples',
            name='author',
            field=models.CharField(choices=[('Z', 'ضیائی'), ('K', 'کارآموز')], default='Z', max_length=1, verbose_name='توسط'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام طرح'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عتوان طرح'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آپدیت'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='video',
            field=models.FileField(upload_to='video/samples', verbose_name='ویدیو طرح'),
        ),
        migrations.AddField(
            model_name='samples',
            name='category',
            field=models.ManyToManyField(related_name='samples', to='samples.category', verbose_name='Category'),
        ),
    ]
