# Generated by Django 4.2.4 on 2023-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_category_alter_samples_options_alter_samples_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
