# Generated by Django 4.2.4 on 2023-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_samples_body_samples_canonical_samples_descriptionog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patterns/'),
        ),
    ]
