# Generated by Django 4.2.4 on 2023-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Sample Page Tag', 'verbose_name_plural': 'Sample Page Tags'},
        ),
        migrations.AlterField(
            model_name='samples',
            name='author',
            field=models.CharField(choices=[('ضیائی', 'ضیائی'), ('کارآموز', 'کارآموز')], default='ضیائی', max_length=100, verbose_name='توسط'),
        ),
    ]
