# Generated by Django 4.2.4 on 2023-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='alt',
            field=models.CharField(default='Type...', max_length=250),
        ),
    ]
