# Generated by Django 4.2.4 on 2023-09-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_samples_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samples',
            options={'ordering': ('-created_at',), 'verbose_name': 'طرح', 'verbose_name_plural': 'طرح ها'},
        ),
    ]
