# Generated by Django 4.2.4 on 2023-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_alter_samples_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samples',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={},
        ),
        migrations.AddField(
            model_name='samples',
            name='cover',
            field=models.FileField(default=models.ImageField(upload_to='images/samples/'), upload_to='images/cover/samples/'),
        ),
        migrations.AddField(
            model_name='samples',
            name='duration',
            field=models.CharField(default='Type...', max_length=200),
        ),
        migrations.AddField(
            model_name='samples',
            name='follow_nofollow',
            field=models.CharField(choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=150),
        ),
        migrations.AddField(
            model_name='samples',
            name='index_noindex',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=150),
        ),
        migrations.AddField(
            model_name='samples',
            name='schema1',
            field=models.TextField(blank=True, null=True, verbose_name='اسکیما'),
        ),
        migrations.AddField(
            model_name='samples',
            name='schema2',
            field=models.TextField(blank=True, null=True, verbose_name='اسکیما'),
        ),
        migrations.AddField(
            model_name='samples',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter:description'),
        ),
        migrations.AddField(
            model_name='samples',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter:title'),
        ),
        migrations.AddField(
            model_name='tags',
            name='canonical',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Canonical'),
        ),
        migrations.AddField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='follow_nofollow',
            field=models.CharField(blank=True, choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Tags', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='tags',
            name='index_noindex',
            field=models.CharField(blank=True, choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='schema1',
            field=models.TextField(blank=True, null=True, verbose_name='اسکیما'),
        ),
        migrations.AddField(
            model_name='tags',
            name='schema2',
            field=models.TextField(blank=True, null=True, verbose_name='اسکیما'),
        ),
        migrations.AddField(
            model_name='tags',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter:description'),
        ),
        migrations.AddField(
            model_name='tags',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter:title'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='extratag',
            field=models.TextField(blank=True, null=True, verbose_name='تگ های جدید'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='image',
            field=models.ImageField(upload_to='images/samples/'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='extratag',
            field=models.TextField(blank=True, null=True, verbose_name='تگ های جدید'),
        ),
    ]
